FROM openjdk:16
EXPOSE 8100
ADD target/currency-conversion-service-docker-185.jar currency-conversion-service-docker-185.jar
ENTRYPOINT ["java","-jar","/currency-conversion-service-docker-185.jar"]